server:
  port: 8084
spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      uri: http://localhost:8888
      profile: dev
    bootstrap:
      enabled: true
    gateway:
      routes:
        - id: solar-service
          uri: lb://solar-service
          predicates:
            - Path=/solar/**
        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/email/**
