apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
      - name: email-service
        image: email-service:latest
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: email-service-service
spec:
  type: NodePort
  selector:
    app: email-service
  ports:
    - protocol: TCP
      port: 8081
      nodePort: 30081
      