apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
    spec:
      containers:
      - name: service-discovery
        image: service-discovery:latest
        ports:
        - containerPort: 8761

---
apiVersion: v1
kind: Service
metadata:
  name: service-discovery-service
spec:
  type: NodePort
  selector:
    app: service-discovery
  ports:
    - protocol: TCP
      port: 8761
      nodePort: 30087
      