apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-service
  template:
    metadata:
      labels:
        app: solar-service
    spec:
      containers:
      - name: solar-service
        image: solar-service:latest
        ports:
        - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: solar-service-service
spec:
  type: NodePort
  selector:
    app: solar-service
  ports:
    - protocol: TCP
      port: 8082
      nodePort: 30082
      